AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Free text search API and indexer for a collection of articles
Parameters:
  TargetBucket:
    Description: Name of S3 bucket to create where search articles should be uploaded (remember s3 bucket names are only lowercase)
    Type: String
  InternalAPIKey: 
    Type: String
    Default: supersecretkey
    Description: Internal API Key that you will use when making requests to update the search index configuration
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  DocumentSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: document_search
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          BUCKET_NAME: !Ref TargetBucket
          INTERNAL_API_KEY: !Ref InternalAPIKey
      Policies:
        - Statement:
            - Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:GetObjectVersion
                - s3:PutObject
                - s3:GetLifecycleConfiguration
                - s3:PutLifecycleConfiguration
              Resource:
                - Fn::Sub:
                    - arn:${AWS::Partition}:s3:::${bucketName}
                    - bucketName:
                        Ref: TargetBucket
                - Fn::Sub:
                    - arn:${AWS::Partition}:s3:::${bucketName}/*
                    - bucketName:
                        Ref: TargetBucket
              Effect: Allow
      Events:
        DocumentSearch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: GET
        DocumentUpload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /add
            Method: ANY
        SearchConfiguration:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /internal/config
            Method: ANY
  DocumentIndexingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: document_indexer
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Policies: AWSLambdaExecute
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          BUCKET_NAME: !Ref TargetBucket
      Policies:
      - Statement:
          - Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
              - s3:GetLifecycleConfiguration
              - s3:PutLifecycleConfiguration
            Resource:
              - Fn::Sub:
                  - arn:${AWS::Partition}:s3:::${bucketName}
                  - bucketName:
                      Ref: TargetBucket
              - Fn::Sub:
                  - arn:${AWS::Partition}:s3:::${bucketName}/*
                  - bucketName:
                      Ref: TargetBucket
            Effect: Allow
      Events:
        DocumentAddedEvent:
         Type: S3
         Properties:
           Bucket: !Ref SearchDocumentsBucket
           Events: s3:ObjectCreated:*
  SearchDocumentsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref TargetBucket
      
Outputs:
  DocumentSearchApi:
    Description: "Deployed API Gateway Endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  DocumentSearchFunction:
    Description: "Serverless Document API Search Function ARN"
    Value: !GetAtt DocumentSearchFunction.Arn

  DocumentIndexingFunction:
    Description: "Serverless Document Search Function ARN"
    Value: !GetAtt DocumentIndexingFunction.Arn

  DocumentCollectionBucket:
    Description: "S3 Bucket for all uploaded documents and indexing information"
    Value: !Ref TargetBucket

 
